name: drag
description: "A drag project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-41.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.1
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.2
  firebase_auth: ^4.14.1
  google_sign_in: ^6.1.6
  table_calendar: ^3.0.9
  cloud_firestore: ^4.13.3
  intl: ^0.18.1
  flutter_date_range_picker: ^0.0.14
  http: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  image_picker: ^1.0.4
  firebase_storage_web: ^3.6.17
  cloud_firestore_web: ^3.8.9
  firebase_core_web: ^2.10.0
  firebase_auth_web: ^5.8.11


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/grab_icon/grab_app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/img/google.png
    - assets/img/
    - assets/icons/grab_icon/
    - assets/icons/
    - assets/icons/grab_icon/4x/
    - assets/icons/progress_icon.gif
